#!/usr/bin/env node
/**
 * Build router/skills-index.json and ROUTER.md from each skill file
 * and the notes in router/intents.json.
 *
 *   node scripts/generate-index.mjs
 *   node scripts/generate-index.mjs --skills-dir ~/my-skills --out-dir .
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { keywordsFrom, parseFrontmatter } from "../lib/frontmatter.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..");

function arg(flag, fallback) {
  const index = process.argv.indexOf(flag);
  return index >= 0 && process.argv[index + 1] ? process.argv[index + 1] : fallback;
}
function expand(value) {
  return value.startsWith("~") ? path.join(process.env.HOME || "", value.slice(1)) : value;
}

const skillsDir = path.resolve(expand(arg("--skills-dir", path.join(repoRoot, "skills"))));
const outDir = path.resolve(expand(arg("--out-dir", repoRoot)));
const intents = JSON.parse(fs.readFileSync(path.join(repoRoot, "router", "intents.json"), "utf8"));

const skillDirs = fs
  .readdirSync(skillsDir)
  .filter((dir) => fs.existsSync(path.join(skillsDir, dir, "SKILL.md")))
  .sort();

const skills = skillDirs.map((dir) => {
  const filePath = path.join(skillsDir, dir, "SKILL.md");
  const text = fs.readFileSync(filePath, "utf8");
  const frontmatter = parseFrontmatter(text);
  const description = (frontmatter.description || "").replace(/\s+/g, " ").trim();
  const oneLine = description.length > 180 ? `${description.slice(0, 177)}...` : description;
  const knowledgeDir = path.join(skillsDir, dir, "knowledge", "current", dir);
  return {
    dir,
    name: frontmatter.name || dir,
    description,
    oneLine,
    keywords: keywordsFrom(`${dir} ${frontmatter.name || ""} ${description}`, frontmatter.keywords || ""),
    hasKnowledge: fs.existsSync(knowledgeDir),
    path: `skills/${dir}/SKILL.md`,
  };
});

const generatedAt = new Date().toISOString();
const index = {
  generated: generatedAt,
  skillsDir: path.relative(outDir, skillsDir) || "skills",
  count: skills.length,
  intents: (intents.rules || []).map((rule) => ({
    id: rule.id,
    skill: rule.skill,
    when: rule.when || [],
    also: rule.also || [],
    why: rule.why || "",
  })),
  skills,
};

fs.mkdirSync(path.join(outDir, "router"), { recursive: true });
fs.writeFileSync(path.join(outDir, "router", "skills-index.json"), `${JSON.stringify(index, null, 2)}\n`);

const lines = [
  "<!-- Generated by scripts/generate-index.mjs. Edit skills or router/intents.json, then re-run. -->",
  "# Skill Router",
  "",
  `> ${skills.length} skills · generated ${generatedAt}`,
  "",
  "A prompt loads every skill whose job phrase appears in it. One job loads one skill. Two jobs load both. This file does not add skills the prompt did not ask for.",
  "",
  "## What each skill is for",
  "",
  "| Skill | Job |",
  "| --- | --- |",
];
for (const rule of intents.rules || []) {
  lines.push(`| \`${rule.skill}\` | ${rule.why || ""} |`);
}
lines.push("", "## Catalog", "", "| Skill | Knowledge | What it does |", "| --- | --- | --- |");
for (const skill of skills) {
  lines.push(`| [\`${skill.dir}\`](${skill.path}) | ${skill.hasKnowledge ? "yes" : ""} | ${skill.oneLine.replace(/\|/g, "\\|")} |`);
}
lines.push("");
fs.writeFileSync(path.join(outDir, "ROUTER.md"), `${lines.join("\n")}\n`);

let rebuilt = 0;
for (const skill of skills.filter((item) => item.hasKnowledge)) {
  const knowledgeDir = path.join(skillsDir, skill.dir, "knowledge", "current", skill.dir);
  const topics = fs.readdirSync(knowledgeDir).filter((file) => file.endsWith(".md") && file !== "_index.md").sort();
  const rows = topics.map((file) => {
    const topicText = fs.readFileSync(path.join(knowledgeDir, file), "utf8");
    const topicFields = parseFrontmatter(topicText);
    const title = topicFields.title || file.replace(/\.md$/, "").replace(/-/g, " ");
    const blurb = (topicFields.description || "").replace(/\|/g, "\\|").slice(0, 120);
    return `| [${file}](./${file}) | ${title.replace(/\|/g, "\\|")} | ${blurb} |`;
  });
  const topicIndex = [
    "---",
    `domain: ${skill.dir}`,
    `documentCount: ${rows.length}`,
    `lastGenerated: ${generatedAt}`,
    "---",
    "",
    `# ${skill.name} — topic index`,
    "",
    "| File | Title | Description |",
    "| --- | --- | --- |",
    ...rows,
    "",
  ];
  fs.writeFileSync(path.join(knowledgeDir, "_index.md"), `${topicIndex.join("\n")}\n`);
  rebuilt += 1;
}

console.error(`Indexed ${skills.length} skills`);
console.error(`Wrote ${path.join(outDir, "router", "skills-index.json")}`);
console.error(`Wrote ${path.join(outDir, "ROUTER.md")}`);
console.error(`Rebuilt ${rebuilt} knowledge indexes`);
